# Generated by Django 4.2.1 on 2023-05-18 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 2, 21, 52, 981943, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
