# Generated by Django 4.2.1 on 2023-05-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subsubject_remove_profile_location_subject_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubject',
            name='sub_subject',
        ),
    ]
