# Generated by Django 4.2.1 on 2023-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_subject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='subsubject',
            name='sub_subject',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
