# Generated by Django 4.2.1 on 2023-05-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_community_pod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
