# Generated by Django 4.2.1 on 2023-05-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='sub',
        ),
        migrations.RenameField(
            model_name='subsubject',
            old_name='sub_subject',
            new_name='sub_sub',
        ),
    ]
