# Generated by Django 4.2.1 on 2023-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_subject_subject_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('sub_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pod',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='members',
        ),
        migrations.AlterField(
            model_name='pod',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
