# Generated by Django 4.2.1 on 2023-05-19 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_topic_remove_pod_creator_remove_pod_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.AddField(
            model_name='pod',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pod',
            name='members',
            field=models.ManyToManyField(related_name='pod_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='key1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='key2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='key3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pod',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
