# Generated by Django 4.2.1 on 2023-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_post_caption_pod_description_pod_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
