# Generated by Django 4.2.1 on 2023-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubSubject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
