# Generated by Django 4.2.1 on 2023-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_subject_delete_subsubject_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
