# Generated by Django 4.2.1 on 2023-05-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_post_sub_post_sub_sub_alter_profile_sub_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='name',
            new_name='podName',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='members',
        ),
        migrations.AddField(
            model_name='profile',
            name='pod',
            field=models.CharField(default='', max_length=50),
        ),
    ]
