# Generated by Django 4.2.1 on 2023-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_name_pod_podname_remove_pod_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='post',
            name='pod',
            field=models.CharField(default='', max_length=100),
        ),
    ]
