# Generated by Django 4.2.1 on 2023-05-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_profile_sub_subject_remove_profile_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='podName',
            new_name='pod',
        ),
    ]
