# Generated by Django 4.2.1 on 2023-05-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_pod_pod_name_pod_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post_images'),
        ),
    ]
