# Generated by Django 4.2.1 on 2023-05-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_followerscount_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
