# Generated by Django 4.2.1 on 2023-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pod',
            field=models.CharField(max_length=50),
        ),
    ]
